export const INIT_DATA_REQUEST = "INIT_DATA_REQUEST";
export const INIT_DATA_SUCCESS = "INIT_DATA_SUCCESS";
export const INIT_DATA_FAILURE = "INIT_DATA_FAILURE";
export const FETCH_PROJECT_REQUEST = "FETCH_PROJECT_REQUEST";
export const FETCH_PROJECT_SUCCESS = "FETCH_PROJECT_SUCCESS";
export const FETCH_PROJECT_FAILURE = "FETCH_PROJECT_FAILURE";
